mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

spring:
  datasource:
    username: root
    password: lhj445
    url: jdbc:mysql://107.173.181.247/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      # 连接地址
      host: 107.173.181.247
      # 端口
      port: 6379
      # 数据库
      database: 0
      # 用户名，如果有
      # username:
      # 密码，如果有
      password: lhj445
      # 连接超时
      connect-timeout: 5s
      # 读超时
      timeout: 5s

      # Lettuce 客户端的配置
      lettuce:
        # 连接池配置
        pool:
          # 最小空闲连接
          min-idle: 0
          # 最大空闲连接
          max-idle: 8
          # 最大活跃连接
          max-active: 8
          # 从连接池获取连接 最大超时时间，小于等于0则表示不会超时
          max-wait: -1ms

  servlet:
    multipart:
      max-file-size: 150MB   # 与file.max-file-size保持一致
      max-request-size: 200MB

logging:
  level:
    com.example.demo1.mapper: debug

mybatis:
  type-aliases-package: com.example.demo1.**.entity
  mapper-locations: classpath:mapper/*.xml
  #用于mybatis在控制台打印sql日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8081

jwt:
  secret-key: "831d758dd71e3654d381061b4d8e79a34555484d481213bc76ec2cb4db5f2545"

file:
#  upload-dir: /var/uploads  # 生产环境建议使用绝对路径
  upload-dir: D:\aaaimage
  max-file-size: 209715200   # 200MB
  allowed-types:            # 允许的文件MIME类型
    - image/jpeg
    - image/png
    - image/gif
    - video/mp4
    - video/quicktime